=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/moml/MoML_1.dtd
<!-- MoML DTD Version 1.1, UC Berkeley -->
<!-- $Id$ -->
<!-- If you update this file, please also update:  -->
<!--    ptweb/xml/dtd/MoML_1.dtd, -->
<!--    ptII/doc/design/src/MoML.fm, -->
<!--    the static field MoML_DTD_1 in MoMLParser.java. -->
<!-- The top-level element can be either model or class. -->

<!ELEMENT model (class | configure | deleteEntity | deletePort |
		deleteRelation | director | doc | entity | import | link |
                property | relation | rendition | unlink)*>
<!ATTLIST model name CDATA #REQUIRED
                class CDATA #IMPLIED>

<!ELEMENT class (class | configure | deleteEntity | deletePort |
		 deleteRelation | director | doc |
                 entity | import | link |
                 property | relation | rendition | unlink)*>
<!ATTLIST class name CDATA #REQUIRED
                extends CDATA #IMPLIED>

<!ELEMENT configure (#PCDATA)>
<!ATTLIST configure source CDATA #IMPLIED>

<!ELEMENT deleteEntity EMPTY>
<!ATTLIST deleteEntity name CDATA #REQUIRED>

<!ELEMENT deletePort EMPTY>
<!ATTLIST deletePort name CDATA #REQUIRED>

<!ELEMENT deleteProperty EMPTY>
<!ATTLIST deleteProperty name CDATA #REQUIRED>

<!ELEMENT deleteRelation EMPTY>
<!ATTLIST deleteRelation name CDATA #REQUIRED>

<!ELEMENT director (configure | property)*>
<!ATTLIST director name CDATA "director"
                   class CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>
<!ATTLIST doc name CDATA "_doc_">

<!ELEMENT entity (class | configure | deleteEntity | deletePort |
		  deleteRelation | director | doc |
                  entity | import | link | port |
                  property | relation | rendition | unlink)*>
<!ATTLIST entity name CDATA #REQUIRED
                 class CDATA #IMPLIED>

<!ELEMENT import EMPTY>
<!ATTLIST import source CDATA #REQUIRED
                 base CDATA #IMPLIED>

<!ELEMENT link EMPTY>
<!ATTLIST link insertAt CDATA #IMPLIED
               port CDATA #REQUIRED
               relation CDATA #REQUIRED
               vertex CDATA #IMPLIED>

<!ELEMENT location EMPTY>
<!ATTLIST location value CDATA #REQUIRED>

<!ELEMENT port (configure | doc | property)*>
<!ATTLIST port class CDATA #IMPLIED
               name CDATA #REQUIRED>

<!ELEMENT property (configure | doc | property)*>
<!ATTLIST property class CDATA #IMPLIED
                    name CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT relation (property | vertex)*>
<!ATTLIST relation name CDATA #REQUIRED
                   class CDATA #IMPLIED>

<!ELEMENT rendition (configure | location | property)*>
<!ATTLIST rendition class CDATA #REQUIRED>

<!ELEMENT unlink EMPTY>
<!ATTLIST unlink index CDATA #IMPLIED
                 insideIndex CDATA #IMPLIED
		 insideIndex CDATA #IMPLIED
                 port CDATA #REQUIRED
                 relation CDATA #REQUIRED>

<!ELEMENT vertex (location | property)*>
<!ATTLIST vertex name CDATA #REQUIRED
                 pathTo CDATA #IMPLIED>

=== maqtech/PtolemyIndustrialControl/ptolemy/domains/de/lib/test/auto/Inhibit.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="" class="ptolemy.actor.TypedCompositeActor">
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 450]">
    </property>
    <property name="_vergilLocation" class="ptolemy.actor.gui.LocationAttribute" value="[104, 102]">
    </property>
    <property name="DE" class="ptolemy.domains.de.kernel.DEDirector">
        <property name="stopTime" class="ptolemy.data.expr.Parameter" value="10.0">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="95.0, 75.0">
        </property>
    </property>
    <entity name="Inhibit" class="ptolemy.domains.de.lib.Inhibit">
        <property name="_location" class="ptolemy.moml.Location" value="290.0, 204.5">
        </property>
    </entity>
    <entity name="Clock" class="ptolemy.actor.lib.Clock">
        <property name="period" class="ptolemy.data.expr.Parameter" value="4.0">
        </property>
        <doc>Create a generalized square wave</doc>
        <property name="_location" class="ptolemy.moml.Location" value="130.0, 174.5">
        </property>
    </entity>
    <entity name="Clock2" class="ptolemy.actor.lib.Clock">
        <property name="period" class="ptolemy.data.expr.Parameter" value="4.0">
        </property>
        <property name="offsets" class="ptolemy.data.expr.Parameter" value="{0.0, 2.0}">
        </property>
        <doc>Create a generalized square wave</doc>
        <property name="_location" class="ptolemy.moml.Location" value="130.0, 240.0">
        </property>
    </entity>
    <entity name="Test" class="ptolemy.actor.lib.Test">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{1.0,5.0,9.0}">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="501.5, 204.5">
        </property>
    </entity>
    <entity name="CurrentTime" class="ptolemy.actor.lib.CurrentTime">
        <property name="_location" class="ptolemy.moml.Location" value="391.5, 204.5">
        </property>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation4" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation5" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation6" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="Inhibit.input" relation="relation"/>
    <link port="Inhibit.output" relation="relation5"/>
    <link port="Inhibit.inhibit" relation="relation4"/>
    <link port="Clock.output" relation="relation"/>
    <link port="Clock2.output" relation="relation4"/>
    <link port="Test.input" relation="relation6"/>
    <link port="CurrentTime.output" relation="relation6"/>
    <link port="CurrentTime.trigger" relation="relation5"/>
</entity>

=== maqtech/PtolemyIndustrialControl/ptolemy/actor/lib/signalprocessing.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="signal processing" class="ptolemy.moml.EntityLibrary">
  <configure>
    <?moml
      <group>
  <doc>Signal processing actors</doc>

  <entity name="DB" class="ptolemy.actor.lib.DB">
  </entity>

<entity name="FIR" class="ptolemy.domains.sdf.lib.FIR">
<doc>FIR filter</doc>
</entity>

<entity name="IIR" class="ptolemy.actor.lib.IIR">
<doc>IIR filter</doc>
</entity>

<entity name="LineCoder" class="ptolemy.domains.sdf.lib.LineCoder">
</entity>

<entity name="RaisedCosine" class="ptolemy.domains.sdf.lib.RaisedCosine">
</entity>

<!-- NOTE: Collect everything that is imported into this one file,
     because when any imported object is dropped into a model, all
     files imported by this library will be imported by the model.
     May as well keep it to one file. -->
<import source="ptolemy/actor/lib/SignalProcessingActors.xml"/>
<entity name="Sinewave" class=".SignalProcessingActors.Sinewave"/>

        <!-- NOTE: javasound actors only work under jdk1.3. -->
        <input source="javasound/index.xml"/>
	<!-- NOTE: This next one is labeled as image processing."-->
        <input source="../../domains/sdf/lib/vq/sdfvqentities.xml"/>

      </group>
    ?>
  </configure>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/org/terraswarm/accessor/test/auto/DerivedAgain.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="DerivedAgain" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="11.0.devel">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={9, 26, 934, 636}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[700, 526]">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0000000000000002">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{339.99999999999983, 252.99999999999963}">
    </property>
    <property name="DE Director" class="ptolemy.domains.de.kernel.DEDirector">
        <property name="stopWhenQueueIsEmpty" class="ptolemy.data.expr.Parameter" value="true">
        </property>
        <property name="synchronizeToRealTime" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{120, 35}">
        </property>
    </property>
    <property name="Annotation" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="Test that a derived accessor can see 2 inheritance levels above it.&#10;&#10;Base3:&#10;exports.baseField = 1;&#10;&#10;Derived3 extends Base3&#10;exports.derivedField = 2;&#10;&#10;DerivedAgain extends Derived3.&#10;&#10;ensure DerivedAgain can access baseField and derivedField">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[5.0, 315.0]">
        </property>
    </property>
    <entity name="SingleEvent" class="ptolemy.actor.lib.SingleEvent">
        <property name="time" class="ptolemy.data.expr.Parameter" value="1.0">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[190.0, 210.0]">
        </property>
    </entity>
    <entity name="Test" class="ptolemy.actor.lib.Test">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{1}">
        </property>
        <property name="requireAllCorrectValues" class="ptolemy.actor.parameters.SharedParameter" value="true">
        </property>
        <property name="trainingMode" class="ptolemy.actor.parameters.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[555.0, 150.0]">
        </property>
    </entity>
    <entity name="Test2" class="ptolemy.actor.lib.Test">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{2}">
        </property>
        <property name="requireAllCorrectValues" class="ptolemy.actor.parameters.SharedParameter" value="true">
        </property>
        <property name="trainingMode" class="ptolemy.actor.parameters.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[550.0, 225.0]">
        </property>
    </entity>
    <entity name="DerivedAgain" class="org.terraswarm.accessor.JSAccessor">
        <property name="script" class="ptolemy.actor.parameters.PortParameter" value="exports.setup = function() {&#10;   extend('Derived3');&#10;   output('out2');&#10;}&#10;&#10;//Override input Handler of base. try to access fields defined in&#10;//base and derived&#10;exports.inputHandler = function() {&#10;   send('out1', this.baseField);&#10;   send('out2', this.derivedField);&#10;}&#10;&#10;exports.initialize = function() {&#10;   Object.getPrototypeOf(exports).initialize.apply(this);&#10;}&#10;&#10;&#10;&#10;">
        </property>
        <property name="accessorSource" class="org.terraswarm.accessor.JSAccessor$ActionableAttribute" value="$CLASSPATH/org/terraswarm/accessor/test/auto/accessors/DerivedAgain.js">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[315.0, 210.0]">
        </property>
        <property name="_expertMode" class="ptolemy.kernel.util.SingletonAttribute">
        </property>
        <port name="in1" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="_showName" class="ptolemy.data.expr.SingletonParameter" value="true">
            </property>
        </port>
        <port name="out1" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
            <property name="_showName" class="ptolemy.data.expr.SingletonParameter" value="true">
            </property>
        </port>
        <port name="out2" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
            <property name="_showName" class="ptolemy.data.expr.SingletonParameter" value="true">
            </property>
        </port>
    </entity>
    <entity name="Display" class="ptolemy.actor.lib.gui.Display">
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={879, 57, 535, 216}, maximized=false}">
        </property>
        <property name="_paneSize" class="ptolemy.actor.gui.SizeAttribute" value="[535, 172]">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[455.0, 95.0]">
        </property>
    </entity>
    <entity name="Display2" class="ptolemy.actor.lib.gui.Display">
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={881, 303, 535, 216}, maximized=false}">
        </property>
        <property name="_paneSize" class="ptolemy.actor.gui.SizeAttribute" value="[535, 172]">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[495.0, 310.0]">
        </property>
    </entity>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
        <property name="width" class="ptolemy.data.expr.Parameter" value="-1">
        </property>
        <vertex name="vertex1" value="{420.0, 155.0}">
        </vertex>
    </relation>
    <relation name="relation4" class="ptolemy.actor.TypedIORelation">
        <property name="width" class="ptolemy.data.expr.Parameter" value="-1">
        </property>
        <vertex name="vertex1" value="[420.0, 220.0]">
        </vertex>
    </relation>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="SingleEvent.output" relation="relation"/>
    <link port="Test.input" relation="relation3"/>
    <link port="Test2.input" relation="relation4"/>
    <link port="DerivedAgain.in1" relation="relation"/>
    <link port="DerivedAgain.out1" relation="relation3"/>
    <link port="DerivedAgain.out2" relation="relation4"/>
    <link port="Display.input" relation="relation3"/>
    <link port="Display2.input" relation="relation4"/>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/actor/gt/controller/ModelUpdater.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE class PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<class name="ModelUpdater" extends="ptolemy.domains.erg.kernel.ERGModalModel">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="7.1.devel">
    </property>
    <property name="_location" class="ptolemy.kernel.util.Location" value="{235, 135}">
    </property>
    <property name="_ignore" class="ptolemy.actor.gt.IgnoringAttribute">
    </property>
    <property name="FileUpdater" class="ptolemy.actor.gt.controller.FileUpdater">
    </property>
    <entity name="_Controller" class="ptolemy.domains.erg.kernel.ERGController">
        <property name="_Director" class="ptolemy.domains.erg.kernel.ERGDirector">
            <property name="_location" class="ptolemy.kernel.util.Location" value="{0.0, 0.0}">
            </property>
        </property>
        <property name="_library" class="ptolemy.moml.LibraryAttribute">
            <configure>
        <entity name="EventLibrary" class="ptolemy.kernel.CompositeEntity"><input source="ptolemy/configs/basicUtilities.xml"></input><entity name="Event" class="ptolemy.domains.erg.kernel.Event"><property name="_controllerFactory" class="ptolemy.vergil.fsm.modal.HierarchicalStateControllerFactory"></property></entity><entity name="Match" class="ptolemy.actor.gt.controller.Match"></entity><entity name="Test" class="ptolemy.actor.gt.controller.Test"></entity><entity name="Transform" class="ptolemy.actor.gt.controller.Transform"></entity><property name="SynchronizeToRealtime" class="ptolemy.domains.erg.lib.SynchronizeToRealtime"><property name="_icon" class="ptolemy.vergil.icon.ValueIcon"><property name="_color" class="ptolemy.actor.gui.ColorAttribute" value="{0.0, 0.0, 1.0, 1.0}"></property></property><property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute"><configure>
                  <svg>
                    <circle cx="3" cy="3" r="2" style="fill:#0000FF"></circle>
                  </svg>
                </configure></property><property name="_editorFactory" class="ptolemy.vergil.toolbox.VisibleParameterEditorFactory"></property></property></entity>
          </configure>
        </property>
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={288, 268, 823, 514}, maximized=false}">
        </property>
        <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 400]">
        </property>
        <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
        </property>
        <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{300.0, 200.0}">
        </property>
        <property name="HostModel" class="ptolemy.actor.gt.controller.ModelAttribute">
            <property name="_icon" class="ptolemy.vergil.icon.EditorIcon">
                <property name="line" class="ptolemy.vergil.kernel.attributes.LineAttribute">
                    <property name="_location" class="ptolemy.kernel.util.Location" value="[1.0, -5.0]">
                    </property>
                    <property name="lineWidth" class="ptolemy.data.expr.Parameter" value="2.0">
                    </property>
                    <property name="x" class="ptolemy.data.expr.Parameter" value="0.0">
                    </property>
                    <property name="y" class="ptolemy.data.expr.Parameter" value="15.0">
                    </property>
                </property>
                <property name="line2" class="ptolemy.vergil.kernel.attributes.LineAttribute">
                    <property name="_location" class="ptolemy.kernel.util.Location" value="[-12.0, 1.0]">
                    </property>
                    <property name="lineWidth" class="ptolemy.data.expr.Parameter" value="2.0">
                    </property>
                    <property name="x" class="ptolemy.data.expr.Parameter" value="12.0">
                    </property>
                    <property name="y" class="ptolemy.data.expr.Parameter" value="-5.0">
                    </property>
                </property>
                <property name="line3" class="ptolemy.vergil.kernel.attributes.LineAttribute">
                    <property name="_location" class="ptolemy.kernel.util.Location" value="[2.0, -4.0]">
                    </property>
                    <property name="lineWidth" class="ptolemy.data.expr.Parameter" value="2.0">
                    </property>
                    <property name="x" class="ptolemy.data.expr.Parameter" value="12.0">
                    </property>
                    <property name="y" class="ptolemy.data.expr.Parameter" value="5.0">
                    </property>
                </property>
                <property name="line4" class="ptolemy.vergil.kernel.attributes.LineAttribute">
                    <property name="_location" class="ptolemy.kernel.util.Location" value="[-11.0, 18.0]">
                    </property>
                    <property name="lineWidth" class="ptolemy.data.expr.Parameter" value="2.0">
                    </property>
                    <property name="x" class="ptolemy.data.expr.Parameter" value="12.0">
                    </property>
                    <property name="y" class="ptolemy.data.expr.Parameter" value="-8.0">
                    </property>
                </property>
                <property name="line5" class="ptolemy.vergil.kernel.attributes.LineAttribute">
                    <property name="_location" class="ptolemy.kernel.util.Location" value="[1.0, 10.0]">
                    </property>
                    <property name="lineWidth" class="ptolemy.data.expr.Parameter" value="2.0">
                    </property>
                    <property name="x" class="ptolemy.data.expr.Parameter" value="12.0">
                    </property>
                    <property name="y" class="ptolemy.data.expr.Parameter" value="8.0">
                    </property>
                </property>
                <property name="ellipse" class="ptolemy.vergil.kernel.attributes.EllipseAttribute">
                    <property name="_location" class="ptolemy.kernel.util.Location" value="1.0, -12.0">
                    </property>
                    <property name="width" class="ptolemy.data.expr.Parameter" value="16.0">
                    </property>
                    <property name="height" class="ptolemy.data.expr.Parameter" value="16.0">
                    </property>
                    <property name="centered" class="ptolemy.data.expr.Parameter" value="true">
                    </property>
                    <property name="fillColor" class="ptolemy.actor.gui.ColorAttribute" value="{1.0, 1.0, 1.0, 1.0}">
                    </property>
                    <property name="_renderLast" class="ptolemy.kernel.util.SingletonAttribute">
                    </property>
                </property>
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="[515.0, 45.0]">
            </property>
        </property>
        <property name="Matched" class="ptolemy.data.expr.Parameter" value="false">
            <property name="_hideName" class="ptolemy.kernel.util.SingletonAttribute">
            </property>
            <property name="_icon" class="ptolemy.vergil.icon.ValueIcon">
                <property name="_color" class="ptolemy.actor.gui.ColorAttribute" value="{0.0, 0.0, 1.0, 1.0}">
                </property>
            </property>
            <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
                <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:blue" y="20">-P-</text>
      </svg>
    </configure>
            </property>
            <property name="_editorFactory" class="ptolemy.vergil.toolbox.VisibleParameterEditorFactory">
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="[500.0, 80.0]">
            </property>
        </property>
        <entity name="init" class="ptolemy.actor.gt.controller.InitContainingModelEvent">
            <property name="isInitialState" class="ptolemy.data.expr.Parameter" value="true">
            </property>
            <property name="isInitialEvent" class="ptolemy.data.expr.Parameter" value="true">
            </property>
            <property name="InitEventIcon" class="ptolemy.vergil.erg.EventIcon">
                <property name="_fill" class="ptolemy.data.expr.Parameter" value="{1.0, 0.8, 0.8, 0.8}">
                </property>
            </property>
            <property name="_hideName" class="ptolemy.data.expr.SingletonParameter" value="true">
            </property>
            <property name="_location" class="ptolemy.kernel.util.Location" value="[65.0, 40.0]">
            </property>
        </entity>
    </entity>
</class>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/apps/hsif/lib/index.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
"http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<!-- Do not Edit - Automatically generated by make -->
<entity name="ptolemy/apps/hsif/lib" class="ptolemy.moml.EntityLibrary">
<doc>HSIF library</doc>
  <configure>
    <?moml
      <group>

<entity name="Action" class="ptolemy.apps.hsif.lib.Action">
<doc></doc>
</entity>

<entity name="AlgEquation" class="ptolemy.apps.hsif.lib.AlgEquation">
<doc></doc>
</entity>

<entity name="BooleanParameter" class="ptolemy.apps.hsif.lib.BooleanParameter">
<doc></doc>
</entity>

<entity name="BooleanVariable" class="ptolemy.apps.hsif.lib.BooleanVariable">
<doc></doc>
</entity>

<entity name="Channel" class="ptolemy.apps.hsif.lib.Channel">
<doc></doc>
</entity>

<entity name="Constraint" class="ptolemy.apps.hsif.lib.Constraint">
<doc></doc>
</entity>

<entity name="DNHA" class="ptolemy.apps.hsif.lib.DNHA">
<doc></doc>
</entity>

<entity name="DiscreteState" class="ptolemy.apps.hsif.lib.DiscreteState">
<doc></doc>
</entity>

<entity name="FlowEquation" class="ptolemy.apps.hsif.lib.FlowEquation">
<doc></doc>
</entity>

<entity name="Guard" class="ptolemy.apps.hsif.lib.Guard">
<doc></doc>
</entity>

<entity name="HybridAutomaton" class="ptolemy.apps.hsif.lib.HybridAutomaton">
<doc></doc>
</entity>

<entity name="IntegerParameter" class="ptolemy.apps.hsif.lib.IntegerParameter">
<doc></doc>
</entity>

<entity name="IntegerVariable" class="ptolemy.apps.hsif.lib.IntegerVariable">
<doc></doc>
</entity>

<entity name="Invariant" class="ptolemy.apps.hsif.lib.Invariant">
<doc></doc>
</entity>

<entity name="Parameter" class="ptolemy.apps.hsif.lib.Parameter">
<doc></doc>
</entity>

<entity name="RealParameter" class="ptolemy.apps.hsif.lib.RealParameter">
<doc></doc>
</entity>

<entity name="RealVariable" class="ptolemy.apps.hsif.lib.RealVariable">
<doc></doc>
</entity>

<entity name="SendAction" class="ptolemy.apps.hsif.lib.SendAction">
<doc></doc>
</entity>

<entity name="Transition" class="ptolemy.apps.hsif.lib.Transition">
<doc></doc>
</entity>

<entity name="UpdateAction" class="ptolemy.apps.hsif.lib.UpdateAction">
<doc></doc>
</entity>

<entity name="Variable" class="ptolemy.apps.hsif.lib.Variable">
<doc></doc>
</entity>
      </group>
    ?>
  </configure>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/configs/gt/gtActorLibrary.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">

<entity name="GraphTransformation" class="ptolemy.moml.EntityLibrary">
  <configure>
    <?moml
      <group>
        <property name="TransformationAttribute" class="ptolemy.actor.gt.TransformationAttribute">
          <property name="_icon" class="ptolemy.vergil.icon.ValueIcon">
            <property name="_color" class="ptolemy.actor.gui.ColorAttribute" value="{0.0, 0.0, 1.0, 1.0}"/>
          </property>
        </property>
        <entity name="ModelGenerator" class="ptolemy.actor.gt.ModelGenerator"/>
        <entity name="ModelView" class="ptolemy.actor.gt.ModelView"/>
        <entity name="TransformationRule" class="ptolemy.actor.gt.TransformationRule"/>
      </group>
    ?>
  </configure>
</entity>
