=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/moml/MoML_1.dtd
<!-- MoML DTD Version 1.1, UC Berkeley -->
<!-- $Id$ -->
<!-- If you update this file, please also update:  -->
<!--    ptweb/xml/dtd/MoML_1.dtd, -->
<!--    ptII/doc/design/src/MoML.fm, -->
<!--    the static field MoML_DTD_1 in MoMLParser.java. -->
<!-- The top-level element can be either model or class. -->

<!ELEMENT model (class | configure | deleteEntity | deletePort |
		deleteRelation | director | doc | entity | import | link |
                property | relation | rendition | unlink)*>
<!ATTLIST model name CDATA #REQUIRED
                class CDATA #IMPLIED>

<!ELEMENT class (class | configure | deleteEntity | deletePort |
		 deleteRelation | director | doc |
                 entity | import | link |
                 property | relation | rendition | unlink)*>
<!ATTLIST class name CDATA #REQUIRED
                extends CDATA #IMPLIED>

<!ELEMENT configure (#PCDATA)>
<!ATTLIST configure source CDATA #IMPLIED>

<!ELEMENT deleteEntity EMPTY>
<!ATTLIST deleteEntity name CDATA #REQUIRED>

<!ELEMENT deletePort EMPTY>
<!ATTLIST deletePort name CDATA #REQUIRED>

<!ELEMENT deleteProperty EMPTY>
<!ATTLIST deleteProperty name CDATA #REQUIRED>

<!ELEMENT deleteRelation EMPTY>
<!ATTLIST deleteRelation name CDATA #REQUIRED>

<!ELEMENT director (configure | property)*>
<!ATTLIST director name CDATA "director"
                   class CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>
<!ATTLIST doc name CDATA "_doc_">

<!ELEMENT entity (class | configure | deleteEntity | deletePort |
		  deleteRelation | director | doc |
                  entity | import | link | port |
                  property | relation | rendition | unlink)*>
<!ATTLIST entity name CDATA #REQUIRED
                 class CDATA #IMPLIED>

<!ELEMENT import EMPTY>
<!ATTLIST import source CDATA #REQUIRED
                 base CDATA #IMPLIED>

<!ELEMENT link EMPTY>
<!ATTLIST link insertAt CDATA #IMPLIED
               port CDATA #REQUIRED
               relation CDATA #REQUIRED
               vertex CDATA #IMPLIED>

<!ELEMENT location EMPTY>
<!ATTLIST location value CDATA #REQUIRED>

<!ELEMENT port (configure | doc | property)*>
<!ATTLIST port class CDATA #IMPLIED
               name CDATA #REQUIRED>

<!ELEMENT property (configure | doc | property)*>
<!ATTLIST property class CDATA #IMPLIED
                    name CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT relation (property | vertex)*>
<!ATTLIST relation name CDATA #REQUIRED
                   class CDATA #IMPLIED>

<!ELEMENT rendition (configure | location | property)*>
<!ATTLIST rendition class CDATA #REQUIRED>

<!ELEMENT unlink EMPTY>
<!ATTLIST unlink index CDATA #IMPLIED
                 insideIndex CDATA #IMPLIED
		 insideIndex CDATA #IMPLIED
                 port CDATA #REQUIRED
                 relation CDATA #REQUIRED>

<!ELEMENT vertex (location | property)*>
<!ATTLIST vertex name CDATA #REQUIRED
                 pathTo CDATA #IMPLIED>

=== maqtech/PtolemyIndustrialControl/ptolemy/domains/sr/lib/test/auto/ClientServer.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="ClientServer" class="ptolemy.actor.TypedCompositeActor">
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[604, 454]">
    </property>
    <property name="_vergilLocation" class="ptolemy.actor.gui.LocationAttribute" value="[102, 100]">
    </property>
    <property name="SR" class="ptolemy.domains.sr.kernel.SRDirector">
        <property name="iterations" class="ptolemy.data.expr.Parameter" value="6">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="71.0, 47.0">
        </property>
    </property>
    <entity name="NonStrictClient" class="ptolemy.domains.sr.lib.NonStrictClient">
        <property name="_location" class="ptolemy.moml.Location" value="267.0, 224.0">
        </property>
        <port name="dataInput" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
        </port>
        <port name="indexOutput" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
        <port name="dataOutput" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
    </entity>
    <entity name="Server" class="ptolemy.domains.sr.lib.Server">
        <property name="index" class="ptolemy.data.expr.Parameter" value="{1, 2, 4, 8, 16}">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="115.0, 120.0">
        </property>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
        </port>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
    </entity>
    <entity name="Test" class="ptolemy.actor.lib.Test">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{1, 2, 4, 8, 16}">
        </property>
        <property name="tolerance" class="ptolemy.data.expr.Parameter" value="1.0E-9">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="385.0, 266.0">
        </property>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="NonStrictClient.dataInput" relation="relation2"/>
    <link port="NonStrictClient.indexOutput" relation="relation"/>
    <link port="NonStrictClient.dataOutput" relation="relation3"/>
    <link port="Server.input" relation="relation"/>
    <link port="Server.output" relation="relation2"/>
    <link port="Test.input" relation="relation3"/>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/actor/lib/security/security.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="security" class="ptolemy.moml.EntityLibrary">
  <configure>
    <?moml
      <group>

        <entity name="AsymmetricDecryption"
                class="ptolemy.actor.lib.security.AsymmetricDecryption">
          <doc>Creates and sends a key to an AsymmetricEncryption
          actor and decrypts incoming data based on a given
          asymmetric algorithm.</doc>
        </entity>
      
        <entity name="AsymmetricEncryption"
                class="ptolemy.actor.lib.security.AsymmetricEncryption">
	  <doc>Receives a key from an AsymmetricDecryption actor and
	  uses it to encrypt a data input based on a given asymmetric
	  algorithm.</doc>
	</entity>  

	<entity name="Decryption"
	        class="ptolemy.actor.lib.security.Decryption">
	  <doc>Creates and sends a key to an encryptor and decrypts
	  incoming data.</doc>
	</entity>  

	<entity name="ServiceInformation"
	        class="ptolemy.actor.lib.security.ServiceInformation">
	  <doc>Determine the cryptographic services available on the
	  system.</doc>
	</entity>  	  

        <entity name="SignatureSigner"
	        class="ptolemy.actor.lib.security.SignatureSigner">
	  <doc>Creates a signature for the given piece of data and
	  creates the key to be sent to the signature verifier.</doc>
        </entity>

        <entity name="SignatureVerifier"
                class="ptolemy.actor.lib.security.SignatureVerifier">
          <doc>Receives a key from an AsymmetricDecryption actor and
          uses it to encrypt a data input based on a given asymmetric
          algorithm.</doc>
        </entity>
	      
        <entity name="SymmetricDecryption"
	        class="ptolemy.actor.lib.security.SymmetricDecryption">
          <doc>Receives a key from a SymmetricEncryption actor and
          uses it to decrypt a data input based on a given symmetric
          algorithm.</doc>
        </entity>

	<entity name="SymmetricEncryption"
                class="ptolemy.actor.lib.security.SymmetricEncryption">
	  <doc>Creates and sends a key to a SymmetricDecryption and
	  encrypts incoming data based on a given symmetric
	  algorithm.</doc>
        </entity>

      </group>
    ?>
  </configure>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/actor/lib/vhdl/test/auto/UnsignedFixConst.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="UnsignedFixConst" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="6.1.devel">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={147, 94, 815, 518}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 400]">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{300.0, 200.0}">
    </property>
    <property name="SR Director" class="ptolemy.domains.sr.kernel.SRDirector">
        <property name="_location" class="ptolemy.kernel.util.Location" value="[175.0, 150.0]">
        </property>
    </property>
    <entity name="Unsigned" class="ptolemy.actor.lib.vhdl.FixConst">
        <property name="outputPrecision" class="ptolemy.data.expr.StringParameter" value="U1.0">
        </property>
        <property name="value" class="ptolemy.data.expr.Parameter" value="0.23456">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[115.0, 240.0]">
        </property>
    </entity>
    <entity name="Test" class="ptolemy.actor.lib.Test">
        <property name="correctValues" class="ptolemy.data.expr.Parameter" value="{}">
        </property>
        <property name="tolerance" class="ptolemy.data.expr.Parameter" value="0">
        </property>
        <property name="trainingMode" class="ptolemy.moml.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{360.0, 250.0}">
        </property>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
        <property name="width" class="ptolemy.data.expr.Parameter" value="1">
        </property>
    </relation>
    <link port="Unsigned.output" relation="relation"/>
    <link port="Test.input" relation="relation"/>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/configs/ergTableauFactory.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<!-- This file contains a single factory, for editing          -->
<!-- Fmv automata.                                       -->
<property name="factoryERG"
	class="ptolemy.actor.gui.PtolemyTableauFactory">
	<property name="Event Relation Graph Editor"
		class="ptolemy.vergil.erg.ERGGraphTableau$Factory">
      <property name="_library" class="ptolemy.moml.LibraryAttribute">
        <configure>
          <entity name="StateLibrary" class="ptolemy.kernel.CompositeEntity">
            <input source="ptolemy/configs/basicUtilities.xml"/>
            <entity name="Event" class="ptolemy.domains.erg.kernel.Event">
              <property name="_centerName" class="ptolemy.kernel.util.Attribute"/>
            </entity>
          </entity>
        </configure>
      </property>
	</property>
	<property name="Tree View"
		class="ptolemy.vergil.tree.TreeTableau$Factory" />
	<property name="XML view"
		class="ptolemy.actor.gui.TextEditorTableau$Factory" />
</property>

=== maqtech/PtolemyIndustrialControl/ptolemy/domains/dt/kernel/test/auto/CTinsideDT1_.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="CTinsideDT2_" class="ptolemy.actor.TypedCompositeActor">
    <property name="DT1" class="ptolemy.domains.dt.kernel.DTDirector">
        <property name="iterations" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="vectorizationFactor" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="period" class="ptolemy.data.expr.Parameter" value="10.0">
        </property>
        <rendition name="_icon" class="ptolemy.vergil.toolbox.EditorIcon">
            <location value="50.0, 33.0"/>
        </rendition>
    </property>
    <entity name="typed composite actor0" class="ptolemy.actor.TypedCompositeActor">
        <rendition name="_icon" class="ptolemy.vergil.toolbox.EditorIcon">
            <location value="177.0, 186.0"/>
        </rendition>
        <property name="CT0" class="ptolemy.domains.ct.kernel.CTMixedSignalDirector">
            <property name="startTime" class="ptolemy.data.expr.Parameter" value="0.0">
            </property>
            <property name="stopTime" class="ptolemy.data.expr.Parameter" value="100000">
            </property>
            <property name="initStepSize" class="ptolemy.data.expr.Parameter" value="0.1">
            </property>
            <property name="minStepSize" class="ptolemy.data.expr.Parameter" value="1.0E-5">
            </property>
            <property name="maxStepSize" class="ptolemy.data.expr.Parameter" value="1.0">
            </property>
            <property name="maxIterations" class="ptolemy.data.expr.Parameter" value="20">
            </property>
            <property name="errorTolerance" class="ptolemy.data.expr.Parameter" value="1.0E-4">
            </property>
            <property name="valueResolution" class="ptolemy.data.expr.Parameter" value="1.0E-6">
            </property>
            <property name="timeResolution" class="ptolemy.data.expr.Parameter" value="1.0E-10">
            </property>
            <property name="ODESolver" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.ExplicitRK23Solver&quot;">
                <property name="style" class="ptolemy.actor.gui.style.EditableChoiceStyle">
                    <property name="choice0" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.ExplicitRK23Solver&quot;">
                    </property>
                    <property name="choice1" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.BackwardEulerSolver&quot;">
                    </property>
                    <property name="choice2" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.ForwardEulerSolver&quot;">
                    </property>
                </property>
            </property>
            <property name="breakpointODESolver" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.DerivativeResolver&quot;">
                <property name="style" class="ptolemy.actor.gui.style.EditableChoiceStyle">
                    <property name="choice0" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.DerivativeResolver&quot;">
                    </property>
                    <property name="choice1" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.BackwardEulerSolver&quot;">
                    </property>
                    <property name="choice2" class="ptolemy.data.expr.Parameter" value="&quot;ptolemy.domains.ct.kernel.solver.ImpulseBESolver&quot;">
                    </property>
                </property>
            </property>
            <property name="runAheadLength" class="ptolemy.data.expr.Parameter" value="0.1">
            </property>
            <rendition name="_icon" class="ptolemy.vergil.toolbox.EditorIcon">
                <location value="49.0, 42.0"/>
            </rendition>
        </property>
        <port name="port4" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
            <property name="location1" class="ptolemy.moml.Location">
                <location value="485.0, 200.0"/>
            </property>
        </port>
        <entity name="Integrator1" class="ptolemy.domains.ct.lib.Integrator">
            <property name="initialState" class="ptolemy.data.expr.Parameter" value="1.0">
            </property>
            <rendition name="_icon" class="ptolemy.vergil.toolbox.EditorIcon">
                <location value="171.0, 89.0"/>
            </rendition>
            <port name="input" class="ptolemy.actor.TypedIOPort">
                <property name="input"/>
            </port>
            <port name="output" class="ptolemy.actor.TypedIOPort">
                <property name="output"/>
            </port>
        </entity>
        <entity name="Integrator2" class="ptolemy.domains.ct.lib.Integrator">
            <property name="initialState" class="ptolemy.data.expr.Parameter" value="1.0">
            </property>
            <rendition name="_icon" class="ptolemy.vergil.toolbox.EditorIcon">
                <location value="257.0, 89.0"/>
            </rendition>
            <port name="input" class="ptolemy.actor.TypedIOPort">
                <property name="input"/>
            </port>
            <port name="output" class="ptolemy.actor.TypedIOPort">
                <property name="output"/>
            </port>
        </entity>
        <entity name="Scale3" class="ptolemy.actor.lib.Scale">
            <property name="factor" class="ptolemy.data.expr.Parameter" value="3">
            </property>
            <rendition name="_icon" class="ptolemy.vergil.toolbox.LibraryIcon">
                <location value="355.0, 90.0"/>
            </rendition>
            <port name="input" class="ptolemy.actor.TypedIOPort">
                <property name="input"/>
            </port>
            <port name="output" class="ptolemy.actor.TypedIOPort">
                <property name="output"/>
            </port>
        </entity>
        <relation name="relation6" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation7" class="ptolemy.actor.TypedIORelation">
        </relation>
        <relation name="relation0" class="ptolemy.actor.TypedIORelation">
            <vertex name="vertex1" class="ptolemy.moml.Vertex">
                <location value="395.0, 200.0"/>
            </vertex>
        </relation>
        <link port="port4" relation="relation0"/>
        <link port="Integrator1.input" relation="relation0"/>
        <link port="Integrator1.output" relation="relation7"/>
        <link port="Integrator2.input" relation="relation7"/>
        <link port="Integrator2.output" relation="relation6"/>
        <link port="Scale3.input" relation="relation6"/>
        <link port="Scale3.output" relation="relation0"/>
    </entity>
    <entity name="CurrentTime2" class="ptolemy.actor.lib.CurrentTime">
        <property name="stopTime" class="ptolemy.data.expr.Parameter" value="0.0">
        </property>
        <rendition name="_icon" class="ptolemy.vergil.toolbox.LibraryIcon">
            <location value="287.0, 287.0"/>
        </rendition>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <entity name="Display4" class="ptolemy.actor.lib.gui.Display">
        <property name="rowsDisplayed" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="columnsDisplayed" class="ptolemy.data.expr.Parameter" value="40">
        </property>
        <rendition name="_icon" class="ptolemy.vergil.toolbox.LibraryIcon">
            <location value="342.0, 187.0"/>
        </rendition>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <entity name="Display5" class="ptolemy.actor.lib.gui.Display">
        <property name="rowsDisplayed" class="ptolemy.data.expr.Parameter" value="10">
        </property>
        <property name="columnsDisplayed" class="ptolemy.data.expr.Parameter" value="40">
        </property>
        <rendition name="_icon" class="ptolemy.vergil.toolbox.LibraryIcon">
            <location value="383.0, 286.0"/>
        </rendition>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" class="ptolemy.moml.Vertex">
            <location value="228.0, 193.0"/>
        </vertex>
    </relation>
    <relation name="relation6" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="typed composite actor0.port4" relation="relation3"/>
    <link port="CurrentTime2.output" relation="relation6"/>
    <link port="CurrentTime2.trigger" relation="relation3"/>
    <link port="Display4.input" relation="relation3"/>
    <link port="Display5.input" relation="relation6"/>
</entity>

=== maqtech/PtolemyIndustrialControl/ptolemy/domains/openmodelica/lib/test/auto/OpenModelicaPltPlot.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="OpenModelicaPltPlot" class="ptolemy.actor.TypedCompositeActor">
    <property name="size" class="ptolemy.data.expr.Parameter" value="25">
    </property>
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="9.1.devel">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={-8, -8, 1382, 744}, maximized=false}">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{430.0, 301.5}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[1154, 628]">
    </property>
    <property name="_icon" class="ptolemy.vergil.icon.EditorIcon">
    </property>
    <property name="_layoutConfiguration" class="ptolemy.vergil.basic.layout.LayoutConfiguration">
    </property>
    <property name="enableBackwardTypeInference" class="ptolemy.data.expr.Parameter" value="true">
        <property name="style" class="ptolemy.actor.gui.style.LineStyle">
        </property>
    </property>
    <property name="Annotation" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="textColor" class="ptolemy.actor.gui.ColorAttribute" value="{0.4,0.4,0.4,1.0}">
        </property>
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="Author: Mana Mirzaei">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[5.0, 500.0]">
        </property>
    </property>
    <property name="Annotation2" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="textSize" class="ptolemy.data.expr.Parameter" value="14">
        </property>
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="This model verifies plotting when the output format is set to the plt.&#10;">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[125.0, 35.0]">
        </property>
    </property>
    <property name="OpenModelica Director" class="ptolemy.domains.openmodelica.kernel.OpenModelicaDirector">
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-40.0, 115.0]">
        </property>
    </property>
    <property name="_expertMode" class="ptolemy.kernel.util.SingletonAttribute">
    </property>
    <property name="Annotation4" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="textSize" class="ptolemy.data.expr.Parameter" value="12">
        </property>
        <property name="textColor" class="ptolemy.actor.gui.ColorAttribute" value="{1.0,0.0,0.0,1.0}">
        </property>
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="This model requires that OpenModelica be installed (see http://www.openmodelica.org).&#10;In addition,  the OPENMODELICAHOME environment variable must be set and the&#10;PATH must be set to include the OPENMODELICAHOME/bin directory.&#10;&#10;Under Mac OS X:&#10;export OPENMODELICAHOME=/opt/openmodelica&#10;export PATH=${OPENMODELICAHOME}/bin:${PATH}">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[335.0, 405.0]">
        </property>
    </property>
    <property name="Annotation3" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="textSize" class="ptolemy.data.expr.Parameter" value="14">
        </property>
        <property name="italic" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="anchor" class="ptolemy.data.expr.StringParameter" value="northwest">
        </property>
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="The output format should be set to the plt.&#10;The processing mode should be set to the batch.&#10;After running the model, the simulation result file &#10;is generated in the plt format &#10;in the OpenModelica dir of the user dir which is located in the dir&#10;named by the java.io.tmpdir property.&#10;Finally, the result is plotted by PxgraphApplication.&#10;&#10;">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[5.0, 180.0]">
        </property>
    </property>
    <entity name="OpenModelica" class="ptolemy.domains.openmodelica.lib.OpenModelica">
        <property name="fileName" class="ptolemy.data.expr.FileParameter" value="dcmotor.mo">
            <display name="File name"/>
        </property>
        <property name="modelName" class="ptolemy.data.expr.StringParameter" value="dcmotor">
            <display name="Model name"/>
        </property>
        <property name="outputFormat" class="ptolemy.data.expr.StringParameter" value="plt">
            <display name="Output format"/>
        </property>
        <property name="_icon" class="ptolemy.vergil.icon.BoxedValueIcon">
            <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="expression">
            </property>
            <property name="displayWidth" class="ptolemy.data.expr.Parameter" value="60">
            </property>
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-25.0, 180.0]">
        </property>
    </entity>
</entity>
