=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/moml/MoML_1.dtd
<!-- MoML DTD Version 1.1, UC Berkeley -->
<!-- $Id$ -->
<!-- If you update this file, please also update:  -->
<!--    ptweb/xml/dtd/MoML_1.dtd, -->
<!--    ptII/doc/design/src/MoML.fm, -->
<!--    the static field MoML_DTD_1 in MoMLParser.java. -->
<!-- The top-level element can be either model or class. -->

<!ELEMENT model (class | configure | deleteEntity | deletePort |
		deleteRelation | director | doc | entity | import | link |
                property | relation | rendition | unlink)*>
<!ATTLIST model name CDATA #REQUIRED
                class CDATA #IMPLIED>

<!ELEMENT class (class | configure | deleteEntity | deletePort |
		 deleteRelation | director | doc |
                 entity | import | link |
                 property | relation | rendition | unlink)*>
<!ATTLIST class name CDATA #REQUIRED
                extends CDATA #IMPLIED>

<!ELEMENT configure (#PCDATA)>
<!ATTLIST configure source CDATA #IMPLIED>

<!ELEMENT deleteEntity EMPTY>
<!ATTLIST deleteEntity name CDATA #REQUIRED>

<!ELEMENT deletePort EMPTY>
<!ATTLIST deletePort name CDATA #REQUIRED>

<!ELEMENT deleteProperty EMPTY>
<!ATTLIST deleteProperty name CDATA #REQUIRED>

<!ELEMENT deleteRelation EMPTY>
<!ATTLIST deleteRelation name CDATA #REQUIRED>

<!ELEMENT director (configure | property)*>
<!ATTLIST director name CDATA "director"
                   class CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>
<!ATTLIST doc name CDATA "_doc_">

<!ELEMENT entity (class | configure | deleteEntity | deletePort |
		  deleteRelation | director | doc |
                  entity | import | link | port |
                  property | relation | rendition | unlink)*>
<!ATTLIST entity name CDATA #REQUIRED
                 class CDATA #IMPLIED>

<!ELEMENT import EMPTY>
<!ATTLIST import source CDATA #REQUIRED
                 base CDATA #IMPLIED>

<!ELEMENT link EMPTY>
<!ATTLIST link insertAt CDATA #IMPLIED
               port CDATA #REQUIRED
               relation CDATA #REQUIRED
               vertex CDATA #IMPLIED>

<!ELEMENT location EMPTY>
<!ATTLIST location value CDATA #REQUIRED>

<!ELEMENT port (configure | doc | property)*>
<!ATTLIST port class CDATA #IMPLIED
               name CDATA #REQUIRED>

<!ELEMENT property (configure | doc | property)*>
<!ATTLIST property class CDATA #IMPLIED
                    name CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT relation (property | vertex)*>
<!ATTLIST relation name CDATA #REQUIRED
                   class CDATA #IMPLIED>

<!ELEMENT rendition (configure | location | property)*>
<!ATTLIST rendition class CDATA #REQUIRED>

<!ELEMENT unlink EMPTY>
<!ATTLIST unlink index CDATA #IMPLIED
                 insideIndex CDATA #IMPLIED
		 insideIndex CDATA #IMPLIED
                 port CDATA #REQUIRED
                 relation CDATA #REQUIRED>

<!ELEMENT vertex (location | property)*>
<!ATTLIST vertex name CDATA #REQUIRED
                 pathTo CDATA #IMPLIED>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/domains/de/demo/AssemblyLine/AssemblyLine.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="AssemblyLine" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="4.1">
    </property>
    <property name="DE Director" class="ptolemy.domains.de.kernel.DEDirector">
        <property name="stopTime" class="ptolemy.data.expr.Parameter" value="50">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[220.0, 60.0]">
        </property>
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={129, 62, 800, 846}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[585, 728]">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{218.5694444444445, 341.8767361111111}">
    </property>
    <property name="Annotation" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="This demo shows how to use the NonInterruptibleTimer actor and Pulse actor to&#10;model an assembly line.&#10;&#10;The Clock actor (Jobs) generates a set of jobs at different times, where no two&#10;jobs happen at the same time. The Pulse actor (ServiceTimes) takes a job &#10;request and produces the service time of the job request. &#10;&#10;The NonInterruptibleTimer actor (Station) takes the service time and sets a&#10;timer. The timer goes off when the service time expires. The timer can not&#10;be interrupted to respond to another input when it is running. &#10;&#10;A job has to be passed along all three stations. &#10;&#10;The Plotter monitors the outputs from Stations plots the times when jobs &#10;leaves the station.&#10;&#10;This model is based on the assembly line example described in &quot;Distributed &#10;Discrete-Event Simulation&quot; by Jayadev Misra, Computer Serveys, Vol. 18, &#10;No. 1, March 1986.">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[-47.5, 375.0]">
        </property>
    </property>
    <property name="ModelID" class="ptolemy.vergil.kernel.attributes.IDAttribute">
        <property name="created" class="ptolemy.kernel.util.StringAttribute" value="Oct 22, 2004 12:00:12 AM">
        </property>
        <property name="lastUpdated" class="ptolemy.kernel.util.StringAttribute" value="Oct 22, 2004 12:19:09 AM">
        </property>
        <property name="author" class="ptolemy.kernel.util.StringAttribute" value="hyzheng">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[760.0, 670.0]">
        </property>
    </property>
    <entity name="Jobs" class="ptolemy.actor.lib.Clock">
        <property name="period" class="ptolemy.data.expr.Parameter" value="Infinity">
        </property>
        <property name="offsets" class="ptolemy.data.expr.Parameter" value="{5.0, 7.0, 30.0, 32.0}">
        </property>
        <property name="values" class="ptolemy.data.expr.Parameter" value="{4, 10, 1, 5}">
        </property>
        <doc>Create a set of pulses</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[15.0, 70.0]">
        </property>
    </entity>
    <entity name="TimedPlotter" class="ptolemy.actor.lib.gui.TimedPlotter">
        <property name="fillOnWrapup" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="legend" class="ptolemy.kernel.util.StringAttribute" value="Station 1,Station 2, Station 3">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[392.5, 290.0]">
        </property>
        <configure>
<?plotml <!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD PlotML 1//EN"
"http://ptolemy.eecs.berkeley.edu/xml/dtd/PlotML_1.dtd">
<plot>
<title>Times when jobs leave work stations.</title>
<xLabel></xLabel>
<yLabel></yLabel>
<xRange min="0.0" max="50.0"/>
<yRange min="0.0" max="3.0"/>
<default connected="no" marks="dots" stems="yes"/>
</plot>?>
        </configure>
    </entity>
    <entity name="ServiceTimes 2" class="ptolemy.actor.lib.Pulse">
        <property name="indexes" class="ptolemy.data.expr.Parameter" value="{0, 1, 2, 3}">
        </property>
        <property name="values" class="ptolemy.data.expr.Parameter" value="{12, 15, 2, 7}">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[40.0, 255.0]">
        </property>
    </entity>
    <entity name="ServiceTimes 3" class="ptolemy.actor.lib.Pulse">
        <property name="indexes" class="ptolemy.data.expr.Parameter" value="{0, 1, 2, 3}">
        </property>
        <property name="values" class="ptolemy.data.expr.Parameter" value="{2, 3, 1, 4}">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[37.5, 340.0]">
        </property>
    </entity>
    <entity name="TimedPlotter2" class="ptolemy.actor.lib.gui.TimedPlotter">
        <property name="fillOnWrapup" class="ptolemy.data.expr.Parameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[330.0, 125.0]">
        </property>
        <configure>
<?plotml <!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD PlotML 1//EN"
"http://ptolemy.eecs.berkeley.edu/xml/dtd/PlotML_1.dtd">
<plot>
<title>Times when jobs arrive.</title>
<xLabel></xLabel>
<yLabel></yLabel>
<xRange min="0.0" max="50.0"/>
<yRange min="0.0" max="50.0"/>
<default connected="no" marks="dots" stems="yes"/>
</plot>?>
        </configure>
    </entity>
    <entity name="ServiceTimes 1" class="ptolemy.actor.lib.Pulse">
        <property name="indexes" class="ptolemy.data.expr.Parameter" value="{0, 1, 2, 3}">
        </property>
        <property name="values" class="ptolemy.data.expr.Parameter" value="{4, 10, 1, 5}">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[35.0, 175.0]">
        </property>
    </entity>
    <entity name="CurrentTime" class="ptolemy.actor.lib.CurrentTime">
        <doc>Output the current time.</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{195, 125}">
        </property>
    </entity>
    <entity name="Station 1" class="ptolemy.domains.de.lib.NonInterruptibleTimer">
        <property name="value" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[130.0, 175.0]">
        </property>
    </entity>
    <entity name="Station 2" class="ptolemy.domains.de.lib.NonInterruptibleTimer">
        <property name="value" class="ptolemy.data.expr.Parameter" value="2">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[135.0, 255.0]">
        </property>
    </entity>
    <entity name="Station 3" class="ptolemy.domains.de.lib.NonInterruptibleTimer">
        <property name="value" class="ptolemy.data.expr.Parameter" value="3">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[132.5, 340.0]">
        </property>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" value="[197.5, 212.5]">
        </vertex>
    </relation>
    <relation name="relation4" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" value="[192.5, 290.0]">
        </vertex>
    </relation>
    <relation name="relation7" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" value="[70.0, 125.0]">
        </vertex>
    </relation>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation8" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation5" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation6" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="Jobs.output" relation="relation7"/>
    <link port="TimedPlotter.input" relation="relation"/>
    <link port="TimedPlotter.input" relation="relation4"/>
    <link port="TimedPlotter.input" relation="relation6"/>
    <link port="ServiceTimes 2.output" relation="relation2"/>
    <link port="ServiceTimes 2.trigger" relation="relation"/>
    <link port="ServiceTimes 3.output" relation="relation5"/>
    <link port="ServiceTimes 3.trigger" relation="relation4"/>
    <link port="TimedPlotter2.input" relation="relation3"/>
    <link port="ServiceTimes 1.output" relation="relation8"/>
    <link port="ServiceTimes 1.trigger" relation="relation7"/>
    <link port="CurrentTime.output" relation="relation3"/>
    <link port="CurrentTime.trigger" relation="relation7"/>
    <link port="Station 1.input" relation="relation8"/>
    <link port="Station 1.output" relation="relation"/>
    <link port="Station 2.input" relation="relation2"/>
    <link port="Station 2.output" relation="relation4"/>
    <link port="Station 3.input" relation="relation5"/>
    <link port="Station 3.output" relation="relation6"/>
</entity>

=== maqtech/PtolemyIndustrialControl/ptolemy/domains/petrinet/kernel/vergilConfiguration.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="configuration" class="ptolemy.actor.gui.Configuration">

  <doc>Configuration to edit and run Ptolemy II Petri net models</doc>

      <!-- The directory of open models, each represented by an effigy. -->
     <entity name="directory" class="ptolemy.actor.gui.ModelDirectory">
     </entity>

  <!-- Factories for effigies. -->
  <entity name="effigyFactory" class="ptolemy.actor.gui.EffigyFactory">
   
    <entity name="Graph Editor" class="ptolemy.actor.gui.PtolemyEffigy$Factory" >
      <entity name="blank" class="ptolemy.actor.TypedCompositeActor"/>
      <!--  entity name="blank" class="ptolemy.domains.petrinet.kernel.PetriNetActor" / -->
    </entity >

    <entity name="FSM Editor" class="ptolemy.actor.gui.PtolemyEffigy$Factory">
      <entity name="blank" class="ptolemy.domains.fsm.kernel.FSMActor">
        <property name="_library" class="ptolemy.moml.LibraryAttribute">
          <configure>
            <entity name="state library" class="ptolemy.kernel.CompositeEntity">
              <entity name="state" class="ptolemy.domains.fsm.kernel.State"/>
            </entity>
          </configure>
        </property>
      </entity>
    </entity>

    <entity name="PetriNet Editor" class="ptolemy.actor.gui.PtolemyEffigy$Factory">
      <entity name="blank" class="ptolemy.domains.petrinet.kernel.PetriNetActor">
        <property name="_library" class="ptolemy.moml.LibraryAttribute">
          <configure>
           <entity name="state library" class="ptolemy.kernel.CompositeEntity">
           <entity name="state" class="ptolemy.domains.fsm.kernel.State"/>
           <entity name="Place" class="ptolemy.domains.petrinet.kernel.Place"/>
           <entity name="Transition" class="ptolemy.domains.petrinet.kernel.Transition"/>
      <entity name="PetrDirector"class="ptolemy.domains.petrinet.kernel.PetriNetDirector"/>
            </entity>
          </configure>
        </property>
      </entity>
    </entity>





    <entity name="HTML Viewer" class="ptolemy.actor.gui.HTMLEffigyFactory"/>
    <entity name="Text Editor" class="ptolemy.actor.gui.TextEffigy$Factory"/>
  </entity>

 



 <!-- Factories for tableaux. -->
  <entity name="tableauFactory" class="ptolemy.actor.gui.TableauFactory">

   
  
    <!-- Factories for tableaux that offer views of Ptolemy II fsms. -->
  
  <entity name="factory1" class="ptolemy.actor.gui.PtolemyTableauFactory">
      <!-- These will appear in the View menu of an fsm tableau. -->
      <entity name="FSM Editor" class="ptolemy.vergil.ptolemy.fsm.FSMGraphTableau$Factory"/>
      <entity name="PetriNet Editor" class="ptolemy.vergil.ptolemy.petrinet.FSMGraphTableau$Factory"/>
      <entity name="Tree View" class="ptolemy.vergil.tree.TreeTableau$Factory"/>
      <entity name="XML view" class="ptolemy.actor.gui.TextEditorTableau$Factory"/>
    </entity>


    <!-- Factories for tableaux that offer views of Ptolemy II entities. -->
    <entity name="factory2" class="ptolemy.actor.gui.PtolemyTableauFactory">
      <!-- These will appear in the View menu of an entity tableau. -->
      <entity name="Graph Editor" class="ptolemy.vergil.ptolemy.kernel.KernelGraphTableau$Factory"/>
      <entity name="Run Window" class="ptolemy.actor.gui.RunTableau$Factory"/>
      <entity name="Tree View" class="ptolemy.vergil.tree.TreeTableau$Factory"/>
      <entity name="XML view" class="ptolemy.actor.gui.TextEditorTableau$Factory"/>
      <entity name="JVM Properties" class="ptolemy.actor.gui.JVMTableau$Factory"/>
    </entity>


    <entity name="HTML Viewer" class="ptolemy.actor.gui.HTMLViewerTableau$Factory">
      <!-- This will appear in the View menu of an entity tableau. -->
      <entity name="Source" class="ptolemy.actor.gui.TextEditorTableau$Factory"/>
    </entity>
    <entity name="Text Editor" class="ptolemy.actor.gui.TextEditorTableau$Factory"/>
    <!-- FIXME: text editor, plot data tableau, etc. -->
  </entity>   

 

 <!-- Main default library -->
  <entity name="actor library" class="ptolemy.kernel.CompositeEntity">

    <!-- Marker so that tree view expands the library. -->
    <property name="_libraryMarker" class="ptolemy.kernel.util.SingletonAttribute"/>

    <!-- Default utilities library. -->
    <class name="utilities" extends="ptolemy.moml.EntityLibrary">
      <configure>
        <?moml
          <group>
    <property name="annotation" class="ptolemy.kernel.util.Attribute">
<property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
            <configure>
           <svg>
           <text x="20" style="font-size:14; font-family:SansSerif; fill:blue" y="20">Double click to edit text.</text>
           </svg>
           </configure>
        </property>
	<!-- The following attribute makes the right editor open -->
	<property name="_controllerFactory" class="ptolemy.vergil.ptolemy.kernel.NodeControllerFactory"/>
	<property name="_editorFactory" class="ptolemy.vergil.toolbox.AnnotationEditorFactory"/>
    </property>

    <!-- Blank composite actor. -->
    <entity name="typed composite actor" class="ptolemy.actor.TypedCompositeActor"/ >
    <!-- entity name="PetriNetActor" class="ptolemy.domains.petrinet.kernel.PetriNetActor"/ --> 

    <entity name="continuous time composite actor" class="ptolemy.domains.ct.kernel.CTCompositeActor"/>
    <entity name="fsm actor" class="ptolemy.domains.fsm.kernel.FSMActor">
        <property name="_library" class="ptolemy.moml.LibraryAttribute">
          <configure>
            <entity name="state library" class="ptolemy.kernel.CompositeEntity">
              <entity name="state" class="ptolemy.domains.fsm.kernel.State"/>
            </entity>
          </configure>
        </property>
    </entity>



  <entity name="PetriNetActor" class="ptolemy.domains.petrinet.kernel.PetriNetActor">
        <property name="_library" class="ptolemy.moml.LibraryAttribute">
          <configure>
            <entity name="state library" class="ptolemy.kernel.CompositeEntity">
              <entity name="state" class="ptolemy.domains.fsm.kernel.State"/>
            </entity>
          </configure>
        </property>
    </entity>



    <entity name="interface automaton" class="ptolemy.domains.fsm.kernel.InterfaceAutomaton">
        <property name="_library" class="ptolemy.moml.LibraryAttribute">
          <configure>
            <entity name="state library" class="ptolemy.kernel.CompositeEntity">
              <entity name="state" class="ptolemy.domains.fsm.kernel.State"/>
            </entity>
          </configure>
        </property>
    </entity>
          </group>
        ?>
      </configure>
    </class>

    <entity name="Place" class="ptolemy.domains.petrinet.kernel.Place"/>
    <entity name="Transition" class="ptolemy.domains.petrinet.kernel.Transition"/>
  <!-- entity name="Weight" class="ptolemy.domains.petrinet.kernel.Weight"/-->

    <!-- Default director library. -->
    <class name="director library" extends="ptolemy.moml.EntityLibrary">
      <configure>
        <?moml
          <group>

      <doc>default director library</doc>
      <property name="PetriNet" class="ptolemy.domains.petrinet.kernel.PetriNetDirector"/>

          </group>
        ?>
      </configure>
    </class>
  </entity>
</entity>

=== maqtech/PtolemyIndustrialControl/ptolemy/domains/ct/demo/Spontaneous/Brownian.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="Brownian" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="5.0-alpha">
    </property>
    <property name="CT Director" class="ptolemy.domains.ct.kernel.CTMixedSignalDirector">
        <property name="startTime" class="ptolemy.data.expr.Parameter" value="0.0">
        </property>
        <property name="stopTime" class="ptolemy.data.expr.Parameter" value="10.0">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[100.0, 60.0]">
        </property>
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={-4, -4, 1032, 742}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[817, 624]">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{408.5, 312.0}">
    </property>
    <entity name="Gaussian" class="ptolemy.actor.lib.Gaussian">
        <doc>Create a sequence of gaussian random variables</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[55.0, 155.0]">
        </property>
    </entity>
    <entity name="Integrator" class="ptolemy.domains.ct.lib.Integrator">
        <property name="_location" class="ptolemy.kernel.util.Location" value="[175.0, 155.0]">
        </property>
    </entity>
    <entity name="Uniform" class="ptolemy.actor.lib.Uniform">
        <property name="upperBound" class="ptolemy.data.expr.Parameter" value="2*PI">
        </property>
        <doc>Create a sequence of uniformly distributed random numbers</doc>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[295.0, 280.0]">
        </property>
    </entity>
    <entity name="Accumulator" class="ptolemy.actor.lib.Accumulator">
        <property name="_location" class="ptolemy.kernel.util.Location" value="[480.0, 220.0]">
        </property>
    </entity>
    <entity name="PolarToComplex" class="ptolemy.actor.lib.conversions.PolarToComplex">
        <property name="_location" class="ptolemy.kernel.util.Location" value="[360.0, 210.0]">
        </property>
    </entity>
    <entity name="ComplexToCartesian" class="ptolemy.actor.lib.conversions.ComplexToCartesian">
        <property name="_location" class="ptolemy.kernel.util.Location" value="[590.0, 220.0]">
        </property>
    </entity>
    <entity name="XYPlotter" class="ptolemy.actor.lib.gui.XYPlotter">
        <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={258, 205, 508, 492}, maximized=false}">
        </property>
        <property name="_plotSize" class="ptolemy.actor.gui.SizeAttribute" value="[500, 435]">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[710.0, 255.0]">
        </property>
        <configure>
<?plotml <!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD PlotML 1//EN"
"http://ptolemy.eecs.berkeley.edu/xml/dtd/PlotML_1.dtd">
<plot>
<title>XYPlotter</title>
<xLabel></xLabel>
<yLabel></yLabel>
<xRange min="-10.305397094253658" max="0.3357711675658381"/>
<yRange min="-6.381520147607295" max="7.821964540853235"/>
</plot>?>
        </configure>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation3" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" value="[230.0, 155.0]">
        </vertex>
    </relation>
    <relation name="relation2" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation4" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation5" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation6" class="ptolemy.actor.TypedIORelation">
    </relation>
    <relation name="relation7" class="ptolemy.actor.TypedIORelation">
    </relation>
    <link port="Gaussian.output" relation="relation"/>
    <link port="Integrator.input" relation="relation"/>
    <link port="Integrator.output" relation="relation3"/>
    <link port="Uniform.output" relation="relation2"/>
    <link port="Uniform.trigger" relation="relation3"/>
    <link port="Accumulator.input" relation="relation4"/>
    <link port="Accumulator.output" relation="relation5"/>
    <link port="PolarToComplex.magnitude" relation="relation3"/>
    <link port="PolarToComplex.angle" relation="relation2"/>
    <link port="PolarToComplex.output" relation="relation4"/>
    <link port="ComplexToCartesian.input" relation="relation5"/>
    <link port="ComplexToCartesian.x" relation="relation6"/>
    <link port="ComplexToCartesian.y" relation="relation7"/>
    <link port="XYPlotter.inputX" relation="relation6"/>
    <link port="XYPlotter.inputY" relation="relation7"/>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/ptolemy/apps/vhdl/vhdl.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="VHDL" class="ptolemy.moml.EntityLibrary">
  <configure>
    <?moml
      <group>
  <doc>Arithmetic and mathematical functions</doc>
  
  <entity name="Concat" class="ptolemy.apps.vhdl.Concat">
  </entity>  
  
  <entity name="Memory" class="ptolemy.apps.vhdl.Memory">
  </entity>
  
  <entity name="Multiplexor" class="ptolemy.apps.vhdl.Multiplexor">
  </entity>
  
  <entity name="Slice" class="ptolemy.apps.vhdl.Slice">
  </entity>

      </group>
    ?>
  </configure>
</entity>

=== maqtech/PtolemyIndustrialControl/trunk/doc/design/src/examples/inconsistentRates.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="inconsistentRates" class="ptolemy.actor.TypedCompositeActor">
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[604, 454]">
    </property>
    <property name="_vergilLocation" class="ptolemy.actor.gui.LocationAttribute" value="[102, 100]">
    </property>
    <property name="SDF" class="ptolemy.domains.sdf.kernel.SDFDirector">
        <property name="iterations" class="ptolemy.data.expr.Parameter" value="0">
        </property>
        <property name="vectorizationFactor" class="ptolemy.data.expr.Parameter" value="1">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="79.0, 42.0">
        </property>
    </property>
    <entity name="Gaussian" class="ptolemy.actor.lib.Gaussian">
        <property name="seed" class="ptolemy.data.expr.Parameter" value="0">
        </property>
        <property name="mean" class="ptolemy.data.expr.Parameter" value="0.0">
        </property>
        <property name="standardDeviation" class="ptolemy.data.expr.Parameter" value="1.0">
        </property>
        <doc>Create a sequence of gaussian random variables</doc>
        <property name="_location" class="ptolemy.moml.Location" value="81.0, 157.0">
        </property>
        <port name="output" class="ptolemy.actor.TypedIOPort">
            <property name="output"/>
        </port>
        <port name="trigger" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <entity name="SequencePlotter" class="ptolemy.actor.lib.gui.SequencePlotter">
        <property name="fillOnWrapup" class="ptolemy.data.expr.Parameter" value="true">
        </property>
        <property name="legend" class="ptolemy.kernel.util.StringAttribute">
        </property>
        <property name="startingDataset" class="ptolemy.data.expr.Parameter" value="0">
        </property>
        <property name="xInit" class="ptolemy.data.expr.Parameter" value="0.0">
        </property>
        <property name="xUnit" class="ptolemy.data.expr.Parameter" value="1.0">
        </property>
        <property name="_location" class="ptolemy.moml.Location" value="302.0, 155.0">
        </property>
        <port name="input" class="ptolemy.actor.TypedIOPort">
            <property name="input"/>
            <property name="multiport"/>
        </port>
    </entity>
    <relation name="relation" class="ptolemy.actor.TypedIORelation">
        <vertex name="vertex1" class="ptolemy.moml.Vertex" value="138.0, 162.0">
        </vertex>
    </relation>
    <link port="Gaussian.output" relation="relation"/>
</entity>
