=== maqtech/PtolemyIndustrialControl/ptolemy/moml/moml.dtd
<!ELEMENT model (attribute | class | configure | doc | director |
                entity | import | link | relation)*>
<!ATTLIST model name CDATA #REQUIRED
                class CDATA #REQUIRED>

<!ELEMENT attribute (doc | configure)*>
<!ATTLIST attribute class CDATA #IMPLIED
                    name CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT class (attribute | configure | director | doc | entity | link)*>
<!ATTLIST class name CDATA #REQUIRED
                extends CDATA #REQUIRED>

<!ELEMENT configure (#PCDATA)>
<!ATTLIST configure source CDATA #IMPLIED>

<!ELEMENT director (attribute | configure)*>
<!ATTLIST director name CDATA "director"
                   class CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>

<!ELEMENT entity (attribute | class | configure | doc |
                  director | entity | rendition | relation)*>
<!ATTLIST entity name CDATA #REQUIRED
                 class CDATA #REQUIRED>

<!ELEMENT import EMPTY>
<!ATTLIST import source CDATA #REQUIRED>

<!ELEMENT link EMPTY>
<!ATTLIST link port CDATA #REQUIRED
               relation CDATA #REQUIRED
               vertex CDATA #IMPLIED>

<!ELEMENT location EMPTY>
<!ATTLIST location x CDATA #REQUIRED
                   y CDATA #IMPLIED
                   z CDATA #IMPLIED>

<!ELEMENT port (doc | configure)*>
<!ATTLIST port name CDATA #REQUIRED
               class CDATA #REQUIRED
               direction (input | output | both) "both">

<!ELEMENT relation (vertex*)>
<!ATTLIST relation name CDATA #REQUIRED
                   class CDATA #REQUIRED>

<!ELEMENT rendition (configure | location)*>
<!ATTLIST rendition class CDATA #REQUIRED>

<!ELEMENT vertex (location?)>
<!ATTLIST vertex name CDATA #REQUIRED
                 pathTo CDATA #IMPLIED>

=== maqtech/PtolemyIndustrialControl/ptolemy/schematic/editor/testschematic.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE model SYSTEM "../../moml/moml.dtd">

<model name="hello world" class="ptolemy.actor.TypedCompositeActor">
<doc>ramp-recorder...  a good first start</doc>

<director name="director" class="ptolemy.domains.sdf.kernel.SDFDirector">
<attribute name="iterations" value="4"/>
</director>

<entity name="Ramp1" class="ptolemy.actor.lib.Ramp">
<attribute name="init" value="0"/>
<attribute name="step" value="4"/>
    <rendition class="ptolemy.schematic.util.LibraryIcon">
	<location x="50" y="50"/>
        <configure>generic.source</configure>
    </rendition>
</entity>

<entity name="Plotter1" class="ptolemy.actor.gui.SequencePlotter">
    <rendition class="ptolemy.schematic.util.LibraryIcon">
	<location x="150" y="50"/>
       	<configure>generic.sink</configure>
    </rendition>
</entity>

<relation name="R1" class="ptolemy.actor.TypedIORelation">
<vertex name="root">
<location x="100" y="50"/>
</vertex>
</relation>

<link port="Plotter1.input" relation="R1"/>
<link port="Ramp1.output" relation="R1"/>

</model>
